server:
  port: 8080
  context-path: /auth
spring:
  data:
    mongodb:
      database: chat
      host: localhost
      port: 27017
  session:
    store-type: none
  mandatory-file-encoding: UTF-8

logging:
  level:
    org.springframework.security: DEBUG

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8080/auth/oauth/token
      userAuthorizationUri: http://localhost:8080/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8080/auth/rest/hello/principal
