server:
  port: 8081
  context-path: /auth
spring:
  data:
    mongodb:
      database: chat
      host: localhost
      port: 27017
  session:
    store-type: none
  mandatory-file-encoding: UTF-8

security:
  basic:
    enabled: false
logging:
  level:
    org.springframework.security: DEBUG
